blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/joefabre/simplebudget/discussions
    about: Ask questions and discuss with other community members
